# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
jobs:
- job: BuildAngular
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'
    
  #- task: DotNetCoreInstaller@0
  #  displayName: 'Use .NET Core sdk 2.2.100'
  #  inputs:
  #    version: 2.2.100
    
  #- task: NuGetToolInstaller@0
  
  #- script: |
  #    echo install globaltool
  #    dotnet tool install --global stankins.console
  #  displayName: install .net global tools
    
  - script: |
      cd angularCards
      npm install -g @angular/cli
      npm install
      ng build --prod --build-optimizer --output-path $(Build.ArtifactStagingDirectory)/site/
      
      
    displayName: 'npm install and build'
    
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop' 
  
- job: BuildMobile
  dependsOn: 
  - BuildAngular
  
  pool:
    vmImage: 'vs2017-win2016'
  
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: drop
      downloadPath: $(Build.ArtifactStagingDirectory)

  - script: |
      call npm install -g q
      call npm install -g cordova
      dir /S /A:D $(Build.ArtifactStagingDirectory) 
      REM rsync -a $(Build.ArtifactStagingDirectory)/site angularCards/www/dist
      robocopy $(Build.ArtifactStagingDirectory)\site\ angularCards\www\dist  /MIR /XD
      cd cordovaCards
      call cordova platform add android
      call cordova build android   
      
    displayName: 'cordova'
  
  - task: CopyFiles@2
    inputs:
        contents: 'cordovaCards/**/app*.apk'
        targetFolder: '$(Build.ArtifactStagingDirectory)/apk'
        flattenFolders: true